[package]
name = "lebedev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.2"
chumsky = "0.9.0"
strum = "0.26.2"
strum_macros = "0.26.2"