version: '2'
services:
  simulavr:
    build: .
    container_name: simulavr
    image: simulavr-img
    ports:
      - "1212:1212"
    volumes:
      - ./avr-project:/avr-project
    working_dir: /avr-project
